package com.happy.friendogly.common;

public enum ErrorCode {

    DEFAULT_ERROR_CODE,
    FAILED_LOAD_SERVER_FIREBASE_CREDENTIALS,
    INVALID_FIREBASE_CREDENTIALS,
    FILE_SIZE_EXCEED,
    NOT_ALLOW_OTHER_FOOTPRINT_CHANGE,
    ;
}
