aws:
  s3:
    bucket-name: ${BUCKET_NAME}
    server:
      endpoint: https://d1m6m0er0dq0qo.cloudfront.net/
      key-prefix: friendogly/
jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-expiration-time: ${JWT_ACCESS_EXPIRATION_TIME}
  refresh-expiration-time: ${JWT_REFRESH_EXPIRATION_TIME}

kakao:
  admin-key: ${KAKAO_ADMIN_KEY}

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true

  endpoints:
    web:
      exposure:
        include: "*"

  server:
    port: 8081

file:
  firebase:
    path: firebase-friendogly-private-key.json

spring:
  rabbitmq:
    host: ${RABBITMQ_PROD_HOST}
    username: ${RABBITMQ_PROD_USERNAME}
    password: ${RABBITMQ_PROD_PASSWORD}
    port: 3100 # initial connection port: use 3100 instead of 5672
    stomp-port: 9100 # STOMP port: use 9100 instead of 61613
  sql:
    init:
      data-locations:
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:test'
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_batch_fetch_size: 100
