spring:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
  application:
    name: friendogly
  sql:
    init:
      encoding: utf-8

file:
  firebase:
    path: firebase-friendogly-private-key.json
