aws:
  s3:
    bucket-name: techcourse-project-2024
    server:
      endpoint: https://d3obq7hxojfffa.cloudfront.net/
      key-prefix: friendogly/
jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-expiration-time: ${JWT_ACCESS_EXPIRATION_TIME}
  refresh-expiration-time: ${JWT_REFRESH_EXPIRATION_TIME}

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true


  endpoints:
    web:
      exposure:
        include: "*"
