aws:
  s3:
    bucket-name: techcourse-project-2024
    mock:
      port: 8100
      endpoint: http://localhost
    server:
      endpoint: https://d3obq7hxojfffa.cloudfront.net/
      key-prefix: friendogly/
