spring:
  config:
    activate:
      on-profile: "local"
    import: "classpath:secrets.yml"
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:database
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  sql.init.mode: always

logging.level.org:
  hibernate:
    SQL: debug
    orm.jdbc.bind: trace

file:
  firebase:
    path: firebase-friendogly-private-key.json
management:
  health:
    rabbit:
      enabled: false
