spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  jpa:
    defer-datasource-initialization: true
  application:
    name: friendogly
  sql:
    init:
      encoding: utf-8

server:
  tomcat:
    accept-count: 5
    max-connections: 50
    threads:
      max: 50