spring:
  config:
    activate:
      on-profile: "local"
    import: "classpath:secrets.yml"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USER_NAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  sql.init.mode: always

logging.level.org:
  hibernate:
    SQL: debug
    orm.jdbc.bind: trace

file:
  firebase:
    path: firebase-friendogly-private-key.json

management:
  health:
    rabbit:
      enabled: false
