aws:
  s3:
    bucket-name: techcourse-project-2024
    server:
      endpoint: https://d3obq7hxojfffa.cloudfront.net/
      key-prefix: friendogly/
jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-expiration-time: ${JWT_ACCESS_EXPIRATION_TIME}
  refresh-expiration-time: ${JWT_REFRESH_EXPIRATION_TIME}

kakao:
  admin-key: ${KAKAO_ADMIN_KEY}

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true

  endpoints:
    web:
      exposure:
        include: "*"

  server:
    port: 8081

file:
  firebase:
    path: firebase-friendogly-private-key.json

spring:
  rabbitmq:
    host: ${RABBITMQ_PROD_HOST} # TODO: 추가
    username: ${RABBITMQ_PROD_USERNAME}
    password: ${RABBITMQ_PROD_PASSWORD}
    stomp-port: 61613
  sql:
    init:
      data-locations:
  datasource:
    writer:
      hikari:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: ${WRITER_MYSQL_URL}
        read-only: false
        username: ${MYSQL_USERNAME}
        password: ${MYSQL_PASSWORD}
    reader:
      hikari:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: ${READER_MYSQL_URL}
        read-only: true
        username: ${MYSQL_USERNAME}
        password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_batch_fetch_size: 100
