aws:
  s3:
    bucket-name: techcourse-project-2024
    server:
      endpoint: https://d3obq7hxojfffa.cloudfront.net/
      key-prefix: friendogly/
jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-expiration-time: ${JWT_ACCESS_EXPIRATION_TIME}
  refresh-expiration-time: ${JWT_REFRESH_EXPIRATION_TIME}

kakao:
  admin-key: ${KAKAO_ADMIN_KEY}

file:
  firebase:
    path: firebase-friendogly-private-key.json

spring:
  rabbitmq:
    host: ${RABBITMQ_HOST}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    port: 3100 # initial connection port: use 3100 instead of 5672
    stomp-port: 9100 # STOMP port: use 9100 instead of 61613
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:/home/ubuntu/h2_test_data;AUTO_SERVER=true
    username: ${H2_CONSOLE_USERNAME}
    password: ${H2_CONSOLE_PASSWORD}
  h2:
    console:
      enabled: true
      path: ${H2_CONSOLE_ENDPOINT}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
  sql:
    init:
      data-locations:
