name: Android Pull Request CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
    paths:
      - 'android/**'

defaults:
  run:
    working-directory: ./android

jobs:
  verify:
    runs-on: ubuntu-latest

    permissions:
      checks: write

      # needed unless run with comment_mode: off
      pull-requests: write

      # only needed for private repository
      contents: read

      # only needed for private repository
      issues: read

      # required by download step to access artifacts API
      actions: read

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Gradle cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Lint Check
        run: ./gradlew ktlintCheck

      - name: Run detekt
        run: ./gradlew detekt

      - name: Upload Event File
        uses: actions/upload-artifact@v3
        with:
            name: Event File
            path: ${{ github.event_path }}

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest --stacktrace

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
            name: Test Results
            path: "**/test-results/**/*.xml"
