name: deploy

on:
  pull_request:
    branches: [ "develop", "fix/be/swagger-connection" ]
  push:
    branches: ['develop']
     
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.1.1

      - name: Grant execute permission for gradlew
        working-directory: ./backend
        run: chmod +x gradlew
        
      - name: Build project using Gradle
        working-directory: ./backend
        run: ./gradlew build

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: friendogly-be-develop-jar
          path: ./backend/build/libs/friendogly-0.0.1-SNAPSHOT.jar
          
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Change permission
        run: |
          sudo chown -R ubuntu:ubuntu /home/ubuntu/actions-runner/_work/2024-friendogly 

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: friendogly-be-develop-jar
          path: ./backend/build/libs

      - name: List all running processes
        run: |
          echo "Listing all running processes..."
          ps aux

      - name: Find Java Application PID
        id: find_pid
        run: |
          pgrep -f friendogly-0.0.1-SNAPSHOT.jar
          lsof -Pan -p 20012 | grep LISTEN
          lsof -Pan -p 20013 | grep LISTEN
          lsof -Pan -p 20014 | grep LISTEN
          
      - name: Find Java Application PID
        run: |
          lsof -Pan -p 20012 | grep LISTEN
          lsof -Pan -p 20013 | grep LISTEN
          lsof -Pan -p 20014 | grep LISTEN
          
      - name: Check if room-esc server is running on port 8080
        id: check-server-on-port
        run: |
          echo "Checking if port 8080 is in use..."
          PID=$(lsof -t -i:8080 || true)
          if [ -n "$PID" ]; then
            echo "Port 8080 is in use by process $PID."
            echo "server_running=true" >> $GITHUB_ENV
            echo "PID=$PID" >> $GITHUB_ENV
          else
            echo "Port 8080 is not in use."
            echo "server_running=false" >> $GITHUB_ENV
          fi

      - name: Stop server if running
        if: env.server_running == 'true'
        run: |
          echo "Stopping server running on port 8080..."
          kill -9 ${{ env.PID }}
          echo "Previous running Server stopped."

      - name: Check if room-esc server is running on port 8080 after stop
        run: |
          PID=$(lsof -t -i:8080 || true)
          if [ -n "$PID" ]; then
            echo "Server is still running with PID: $PID"
            exit 1
          else
            echo "Server successfully stopped."
          fi

      - name: Start server
        run: |
          cd backend/build/libs
          ls -l friendogly-0.0.1-SNAPSHOT.jar
          sudo nohup java -jar friendogly-0.0.1-SNAPSHOT.jar > /dev/null 2>&1 &
          echo "Latest Backend API Server started."
