name: backend-ci

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
    # paths:
    #  - 'backend/**'

defaults:
  run:
   working-directory: ./backend

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      checks: write

      # needed unless run with comment_mode: off
      pull-requests: write

      # only needed for private repository
      contents: read

      # only needed for private repository
      issues: read

      # required by download step to access artifacts API
      actions: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.1.1

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: 테스트 결과를 PR에 코멘트로 등록합니다
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: "**/test-results/**/*.xml"


      - name: 실패 테스트결과의 원인을 Report 합니다
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: "**/test-results/**/*.xml"
          token: ${{ github.token }}
