name: deploy

on:
  pull_request:
    branches: [ "develop" ]
  push:
    branches: ["develop"]
    paths:
      - "backend/**"

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "corretto"

      # - name: Setup Gradle
      #   uses: gradle/actions/setup-gradle@v3
      #   with:
      #     gradle-version: 8.1.1
      - name: Create google-services.json
        env:
          FIREBASE_FRIENDOGLY_PRIVATE_KEY: ${{ secrets.FIREBASE_FRIENDOGLY_PRIVATE_KEY }}
        run: |
          touch ../backend/src/main/resources/firebase-friendogly-private-key.json
          echo FIREBASE_FRIENDOGLY_PRIVATE_KEY >> ./backend/src/main/resources/firebase-friendogly-private-key.json
          # cat ../backend/src/main/resources/firebase-friendogly-private-key.json

      - name: Grant execute permission for gradlew
        working-directory: ./backend
        run: chmod +x gradlew

      - name: Build project using Gradle
        working-directory: ./backend
        run: ./gradlew build

      # - name: Upload build artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: friendogly-be-develop-jar
      #     path: ./backend/build/libs/friendogly-0.0.1-SNAPSHOT.jar

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Change permission
        run: |
          sudo chown -R ubuntu:ubuntu /home/ubuntu/actions-runner/_work/2024-friendogly

      # - name: Download build artifact
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: friendogly-be-develop-jar
      #     path: ./backend/build/libs

      - name: Find Java Application PID And Kill PID
        id: find_pid
        run: |
          sudo pgrep -f friendogly-0.0.1-SNAPSHOT.jar | xargs sudo kill -9 | true

      - name: Check if room-esc server is running on port 8080 after stop
        run: |
          PID=$(lsof -t -i:8080 || true)
          if [ -n "$PID" ]; then
            echo "Server is still running with PID: $PID"
            exit 1
          else
            echo "Server successfully stopped."
          fi

      - name: Start server
        run: |
          cd backend/build/libs
          echo "File creation time(KR-09:00):"
          ls -l --time=ctime friendogly-0.0.1-SNAPSHOT.jar
          sudo nohup java -jar friendogly-0.0.1-SNAPSHOT.jar --spring.profiles.active=dev --jwt.secret-key=${{ secrets.JWT_SECRET_KEY }} --jwt.access-expiration-time=${{ secrets.JWT_ACCESS_EXPIRATION_TIME }} --jwt.refresh-expiration-time=${{ secrets.JWT_REFRESH_EXPIRATION_TIME }} &
          echo "start backend server"
