name: backend-ci

on:
  pull_request:

defaults:
  run:
    working-directory: ./backend

jobs:
  build:
    runs-on: self-hosted-dev
    permissions:
      checks: write
      pull-requests: write
      contents: read
      issues: read
      actions: read

    steps:
      - name: Set up JDK 17
        run: |
          # 쉘 스크립트 생성
          echo '#!/bin/bash' > my_script.sh
          echo 'echo "The secret is: $TEST_KEY"' >> my_script.sh
          echo 'echo "$TEST_KEY" > secret_output.txt' >> my_script.sh  # TEST_KEY를 출력한 파일 생성
          chmod +x my_script.sh  # 스크립트에 실행 권한 부여

        env:
          TEST_KEY: ${{ secrets.TEST_KEY }}

      - name: Execute the script
        run: |
          ./my_script.sh
        env:
          TEST_KEY: ${{ secrets.TEST_KEY }}

